config/routes.rb
Heroku::Application.routes.draw do
  devise_for :authors

  resources :users

  get "home/index"

   root :to => "home#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/registrations_controller.rb
class Devise::RegistrationsController < ApplicationController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy]
  include Devise::Controllers::InternalHelpers

  # GET /resource/sign_up
  def new
    build_resource({})
    render_with_scope :new
  end

  # POST /resource/sign_up
   def create
    if !verify_recaptcha
      flash.delete :recaptcha_error
      build_resource
      resource.valid?
      resource.errors.add(:base, "There was an error with the recaptcha code below. Please re-enter the code and click submit.")
      clean_up_passwords(resource)
      respond_with_navigational(resource) { render_with_scope :new }
    else
      flash.delete :recaptcha_error
      super
    end
  end



  # GET /resource/edit
  def edit
    render_with_scope :edit
  end

  # PUT /resource
  def update
    if resource.update_with_password(params[resource_name])
      set_flash_message :notice, :updated
      redirect_to after_sign_in_path_for(self.resource)
    else
      clean_up_passwords(resource)
      render_with_scope :edit
    end
  end

  # DELETE /resource
  def destroy
    resource.destroy
    set_flash_message :notice, :destroyed
    sign_out_and_redirect(self.resource)
  end

  protected

    # Authenticates the current scope and gets a copy of the current resource.
    # We need to use a copy because we don't want actions like update changing
    # the current user in place.
    def authenticate_scope!
      send(:"authenticate_#{resource_name}!")
      self.resource = resource_class.find(send(:"current_#{resource_name}").id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all.paginate(:page =>params[:page], :per_page => 2) 

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    if verify_recaptcha :private_key => '6LdMmsYSAAAAAHzIWZ3s5vk5pCoIMarn3v2uAIEQ'
      if @user.save
        respond_to do |format|
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
        end
      else
        respond_to do |format|
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>public Articles</h1>
<p>
Please sign in to add your articles and to see your articles.<br> It is a public articles spot to share </p>
<% if !author_signed_in? %>
<p> sign in to add articles </p>
<% end %>
<% if author_signed_in? %>
<%= link_to "Add Articles", users_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heroku</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  
  <%= csrf_meta_tag %>
</head>
<body background="/images/green.jpg">
 <% if author_signed_in? %>
Signed in as <%= current_author.email %>. Not you?
<%= link_to "Sign out", destroy_author_session_path %>
<% else %>
<%= link_to "Sign up", new_author_registration_path %> or <%= link_to "sign in", new_author_session_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Article %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :Content %><br />
    <%= f.text_area :address %>
  </div>
  <%= recaptcha_tags :public_key => '6LdMmsYSAAAAACZIp1f-YsaO0-08_ogsSDieDrs4' %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<center><h1>Listing Artilces</h1></center>

<hr/>
<%= link_to 'New Article', new_user_path %>

<% @users.each do |user| %>
<% if author_signed_in? %>
  <table>
    <tr><td>Article:</td>
    <td><%= user.name %><td></tr><br>
    <tr><td>Title:</td>
    <td><%= user.mail %></td></tr><br>
    <tr><td>Content:</td>
    <td><%= user.address %></td></tr><br>
    <tr><td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr><br>
<% end %>
<% end %>
</table>
<br>
<br>
<hr/>
<%= will_paginate(@users) %>

<br />

app/views/users/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<center>
<h1> Article details </h1>
<hr/>
</center>
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @user.name %>
</p>

<p>
  <b>Title:</b>
  <%= @user.mail %>
</p>
<p>
  <b>Content:</b>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<hr/>